version: "3.8"
services:
  db:
    image: postgres:16
    container_name: expense_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    container_name: expense_backend
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./backend:/app
    command: ["npm", "run", "dev"]

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    container_name: expense_frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "host"]

volumes:
  postgres_data:
